/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Features */
        get: operations["list_features_api_admin_features_get"];
        put?: never;
        /** Add Feature */
        post: operations["add_feature_api_admin_features_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Feature */
        delete: operations["delete_feature_api_admin_features__feature_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Modules */
        get: operations["list_modules_api_admin_modules_get"];
        put?: never;
        /** Add Module */
        post: operations["add_module_api_admin_modules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Module */
        delete: operations["delete_module_api_admin_modules__module_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/product-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Lines */
        get: operations["list_product_lines_api_admin_product_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/product-lines/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Product Line
         * @description Update SLA overrides (and is_active) for a product line.
         *
         *     Send `null` to a field to clear the override (revert to SLAWatcher
         *     builtin default).
         */
        patch: operations["patch_product_line_api_admin_product_lines__code__patch"];
        trace?: never;
    };
    "/api/admin/scopes/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Features */
        get: operations["list_features_api_admin_scopes_features_get"];
        put?: never;
        /** Add Feature */
        post: operations["add_feature_api_admin_scopes_features_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scopes/features/{scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Feature */
        delete: operations["delete_feature_api_admin_scopes_features__scope_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scopes/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_api_admin_scopes_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scopes/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Modules */
        get: operations["list_modules_api_admin_scopes_modules_get"];
        put?: never;
        /** Add Module */
        post: operations["add_module_api_admin_scopes_modules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scopes/modules/{scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Module */
        delete: operations["delete_module_api_admin_scopes_modules__scope_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_admin_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/feishu/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feishu Departments
         * @description List immediate child departments of `parent_id` (default: root='0').
         *
         *     Frontend uses this to lazily expand the org tree node-by-node.
         */
        get: operations["list_feishu_departments_api_admin_users_feishu_departments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/feishu/departments/{department_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feishu Department Users
         * @description List users directly under a Feishu department, marking which are
         *     already in our local users table (`already_synced=True`) so the UI can
         *     show them differently.
         *
         *     Uses `open_department_id` as `department_id` (Feishu accepts both for
         *     most contact APIs, but open id is preferred for tenant-scoped browsing).
         */
        get: operations["list_feishu_department_users_api_admin_users_feishu_departments__department_id__users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/sync-from-feishu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync From Feishu
         * @description Bulk-pull users from Feishu contact API and upsert into local users.
         *
         *     Provide either `department_id` (sync all members of a Feishu dept) OR
         *     `open_ids` (sync specific users). Mutually exclusive: must give one.
         */
        post: operations["sync_from_feishu_api_admin_users_sync_from_feishu_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Detail */
        get: operations["get_user_detail_api_admin_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/admin/users/{user_id}/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Partner */
        post: operations["add_partner_api_admin_users__user_id__partners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/partners/{partner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Partner */
        delete: operations["remove_partner_api_admin_users__user_id__partners__partner_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/supervisor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Supervisor */
        post: operations["set_supervisor_api_admin_users__user_id__supervisor_post"];
        /** Clear Supervisor */
        delete: operations["clear_supervisor_api_admin_users__user_id__supervisor_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/feishu/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feishu Callback
         * @description Exchange Feishu auth code for our JWT and redirect browser to frontend.
         *
         *     Browser arrives here as a GET (Feishu's standard OAuth2 redirect). We
         *     exchange the code, sign a JWT, and 302 to the frontend SPA with token
         *     in URL fragment (so the token never reaches our server logs).
         *
         *     Side effect: upserts users row (creates on first login).
         */
        get: operations["feishu_callback_api_auth_feishu_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/feishu/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feishu Login Url
         * @description Return the Feishu OAuth2 authorize URL.
         */
        get: operations["feishu_login_url_api_auth_feishu_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Customers */
        get: operations["search_customers_api_customers_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hub-issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hub Issues */
        get: operations["list_hub_issues_api_hub_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hub-issues/{hub_issue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hub Issue */
        get: operations["get_hub_issue_api_hub_issues__hub_issue_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Metrics */
        get: operations["dashboard_metrics_api_metrics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supervisor/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inbox */
        get: operations["list_inbox_api_supervisor_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supervisor/notifications/{notification_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ack Notification */
        post: operations["ack_notification_api_supervisor_notifications__notification_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supervisor/relink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relink Ticket */
        post: operations["relink_ticket_api_supervisor_relink_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket History */
        get: operations["get_ticket_history_api_tickets__ticket_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/ksm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ksm Webhook
         * @description KSM webhook receiver.
         *
         *     Two payload modes (the endpoint accepts both, KSM only sends the first):
         *
         *     1. **Lightweight ping** (production KSM contract per doc § 二):
         *        `{billId|id, noticeNum, subscribeNum}` → store latest pair → schedule
         *        BackgroundTask to call subscribeCallback and ingest → return
         *        `{"code": 0}` immediately.
         *
         *     2. **Full payload** (legacy / tests / xlsx replay):
         *        caller already provides title/content/productLineCode/...; ingest
         *        synchronously and still return `{"code": 0}` (KSM contract).
         *
         *     Per doc: 校验三个字段均不为空，否则忽略（log warning + 200）—
         *     important so KSM doesn't retry malformed pushes.
         */
        post: operations["ksm_webhook_webhook_ksm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/zammad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zammad Webhook */
        post: operations["zammad_webhook_webhook_zammad_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/zhichi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zhichi Webhook */
        post: operations["zhichi_webhook_webhook_zhichi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckResponse */
        AckResponse: {
            /**
             * Acknowledged At
             * Format: date-time
             */
            acknowledged_at: string;
            /** Notification Id */
            notification_id: number;
        };
        /** CheckOut */
        CheckOut: {
            /** Error */
            error?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Required */
            required: boolean;
        };
        /** CountsOut */
        CountsOut: {
            /** Customers Total */
            customers_total: number;
            /** Hub Issues Total */
            hub_issues_total: number;
            /** Notifications Pending */
            notifications_pending: number;
            /** Tickets Active */
            tickets_active: number;
            /** Tickets Total */
            tickets_total: number;
            /** Users Total */
            users_total: number;
        };
        /** CustomerDedupOut */
        CustomerDedupOut: {
            /** Identities Matched */
            identities_matched: number;
            /** Identities Total */
            identities_total: number;
            /** Match Rate */
            match_rate: number;
            /** Target */
            target: string;
        };
        /**
         * CustomerDetail
         * @description Full identity-graph payload for /customers/:id detail page.
         */
        CustomerDetail: {
            customer: components["schemas"]["CustomerSummary"];
            /** Identities */
            identities: components["schemas"]["IdentityOut"][];
            /** Merged Into Chain */
            merged_into_chain: number[];
        };
        /** CustomerSummary */
        CustomerSummary: {
            /** Company */
            company: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /** Id */
            id: number;
            /** Merged Into Customer Id */
            merged_into_customer_id: number | null;
            /** Primary Contact */
            primary_contact: {
                [key: string]: unknown;
            } | null;
        };
        /** DashboardOut */
        DashboardOut: {
            counts: components["schemas"]["CountsOut"];
            customer_dedup: components["schemas"]["CustomerDedupOut"];
            routing: components["schemas"]["RoutingOut"];
            sla: components["schemas"]["SLAOut"];
            supervisor: components["schemas"]["app__api__metrics__SupervisorOut"];
            webhook_intake: components["schemas"]["WebhookIntakeOut"];
        };
        /** FeatureIn */
        FeatureIn: {
            /** Name */
            name: string;
        };
        /** FeatureOut */
        FeatureOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
        };
        /** FeatureScopeIn */
        FeatureScopeIn: {
            /** Feature */
            feature: string;
            /** User Id */
            user_id: number;
        };
        /** FeatureScopeOut */
        FeatureScopeOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Feature */
            feature: string;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
        };
        /**
         * FeishuContactUserOut
         * @description One user under a department in the org-tree browser, annotated with
         *     sync status so the UI can grey-out already-synced rows.
         */
        FeishuContactUserOut: {
            /** Already Synced */
            already_synced: boolean;
            /** Email */
            email: string;
            /** Employee No */
            employee_no: string;
            /** Is Activated */
            is_activated: boolean;
            /** Local User Id */
            local_user_id: number | null;
            /** Mobile */
            mobile: string;
            /** Name */
            name: string;
            /** Open Id */
            open_id: string;
        };
        /**
         * FeishuDeptOut
         * @description One department node in the org-tree browser.
         */
        FeishuDeptOut: {
            /** Department Id */
            department_id: string;
            /** Member Count */
            member_count: number;
            /** Name */
            name: string;
            /** Open Department Id */
            open_department_id: string;
            /** Parent Department Id */
            parent_department_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryEvent
         * @description One row in the merged ticket timeline.
         *
         *     Two `kind` values are emitted:
         *       - 'status'        — a status_history transition (from→to)
         *       - 'hub_issue_link' — a ticket_hub_issue_history row (effective_from start
         *                            of an association; effective_to non-null = closed)
         *
         *     Sorted by `occurred_at` ascending in the response (oldest → newest); the
         *     frontend reverses for display.
         */
        HistoryEvent: {
            /** Change Reason */
            change_reason?: string | null;
            /** Changed By */
            changed_by?: string | null;
            /** Effective To */
            effective_to?: string | null;
            /** From Status */
            from_status?: string | null;
            /** Hub Issue Id */
            hub_issue_id?: number | null;
            /** Human Confirmed */
            human_confirmed?: boolean | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "status" | "hub_issue_link";
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            } | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason?: string | null;
            /** To Status */
            to_status?: string | null;
        };
        /** HistoryOut */
        HistoryOut: {
            /** Action */
            action: string;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Changed By */
            changed_by: number;
            /** Id */
            id: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Scope Type */
            scope_type: string;
            /** User Id */
            user_id: number;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryEvent"][];
            /** Ticket Id */
            ticket_id: number;
        };
        /** HubIssueDetail */
        HubIssueDetail: {
            /** Actual Released At */
            actual_released_at: string | null;
            /** Actual Resolved At */
            actual_resolved_at: string | null;
            /** Assigned User Id */
            assigned_user_id: number | null;
            /** Canonical Body */
            canonical_body: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Customer Verified At */
            customer_verified_at: string | null;
            /** Expected Released At */
            expected_released_at: string | null;
            /** Expected Resolved At */
            expected_resolved_at: string | null;
            /** Feishu Task Id */
            feishu_task_id: string | null;
            /** Feishu Task Status */
            feishu_task_status: string | null;
            /** Feishu Task Synced At */
            feishu_task_synced_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Id */
            id: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Linear Identifier */
            linear_identifier: string | null;
            /** Linear Status */
            linear_status: string | null;
            /** Linear Uuid */
            linear_uuid: string | null;
            /**
             * Linked Tickets
             * @default []
             */
            linked_tickets: components["schemas"]["LinkedTicket"][];
            /** Module */
            module: string | null;
            /** Occurrence Count */
            occurrence_count: number;
            /** Priority */
            priority: string | null;
            /** Product */
            product: string | null;
            /** Product Line Code */
            product_line_code: string | null;
            /** Reply Authored By */
            reply_authored_by: string | null;
            /** Reply Content */
            reply_content: string | null;
            /** Reply Content Version */
            reply_content_version: number;
            /** Reply Updated At */
            reply_updated_at: string | null;
            /** Scheduled Iteration */
            scheduled_iteration: string | null;
            /** Short Code */
            short_code: string;
            /** Status */
            status: string;
            /** Supersede Reason */
            supersede_reason: string | null;
            /** Superseded By Hub Issue Id */
            superseded_by_hub_issue_id: number | null;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** HubIssueListResponse */
        HubIssueListResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["HubIssueSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** HubIssueSummary */
        HubIssueSummary: {
            /** Actual Resolved At */
            actual_resolved_at: string | null;
            /** Assigned User Id */
            assigned_user_id: number | null;
            /** Closed At */
            closed_at: string | null;
            /** Expected Resolved At */
            expected_resolved_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Id */
            id: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Module */
            module: string | null;
            /** Occurrence Count */
            occurrence_count: number;
            /** Priority */
            priority: string | null;
            /** Product */
            product: string | null;
            /** Product Line Code */
            product_line_code: string | null;
            /** Short Code */
            short_code: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** IdentityOut */
        IdentityOut: {
            /** Customer Id */
            customer_id: number;
            /** Email */
            email: string | null;
            /** Erp Uid */
            erp_uid: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Human Confirmed */
            human_confirmed: boolean;
            /** Id */
            id: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Mobile */
            mobile: string | null;
            /** Raw Name */
            raw_name: string | null;
            /** Resolved By Key */
            resolved_by_key: string;
            /** Source Code */
            source_code: string;
            /** Source Custom Id */
            source_custom_id: string | null;
            /** Source User Id */
            source_user_id: string | null;
        };
        /** InboxItem */
        InboxItem: {
            /** Channel */
            channel: string;
            /** Id */
            id: number;
            /** Notify Type */
            notify_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Related Entity Id */
            related_entity_id: number | null;
            /** Related Entity Type */
            related_entity_type: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /** InboxResponse */
        InboxResponse: {
            /** Items */
            items: components["schemas"]["InboxItem"][];
        };
        /**
         * IngestResponse
         * @description Used by zhichi / zammad webhooks (synchronous response shape).
         */
        IngestResponse: {
            /**
             * Assigned User Ids
             * @default []
             */
            assigned_user_ids: number[];
            /** Deduped */
            deduped: boolean;
            /** Routing Decision */
            routing_decision: string;
            /** Short Code */
            short_code: string;
            /** Ticket Id */
            ticket_id: number;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * KSMAck
         * @description KSM expects {"code": 0} as the ack — anything else is treated as a
         *     delivery failure and KSM will retry.
         */
        KSMAck: {
            /**
             * Code
             * @default 0
             */
            code: number;
        };
        /** LinkedTicket */
        LinkedTicket: {
            /** Id */
            id: number;
            /** Short Code */
            short_code: string;
            /** Source Code */
            source_code: string | null;
            /** Source Ticket Id */
            source_ticket_id: string | null;
            /** Status */
            status: string;
        };
        /** LoginUrlResponse */
        LoginUrlResponse: {
            /** Authorize Url */
            authorize_url: string;
        };
        /** ModuleIn */
        ModuleIn: {
            /** Name */
            name: string;
            /** Product Line Code */
            product_line_code: string;
        };
        /** ModuleOut */
        ModuleOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Product Line Code */
            product_line_code: string;
        };
        /** ModuleScopeIn */
        ModuleScopeIn: {
            /** Module */
            module: string;
            /** Product Line Code */
            product_line_code: string;
            /** User Id */
            user_id: number;
        };
        /** ModuleScopeOut */
        ModuleScopeOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Module */
            module: string;
            /** Product Line Code */
            product_line_code: string;
            /** User Id */
            user_id: number;
        };
        /** PartnerIn */
        PartnerIn: {
            /** Partner Id */
            partner_id: number;
        };
        /** PartnerRowOut */
        PartnerRowOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ProductLineOut */
        ProductLineOut: {
            /** Code */
            code: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Sla Reply Hours */
            sla_reply_hours?: number | null;
            /** Sla Resolve Hours */
            sla_resolve_hours?: number | null;
        };
        /**
         * ProductLinePatch
         * @description PATCH body for /api/admin/product-lines/{code}.
         *
         *     NULL on either field clears the override (falls back to SLAWatcher
         *     defaults). Pass `0` is rejected — use `null` to clear.
         */
        ProductLinePatch: {
            /** Is Active */
            is_active?: boolean | null;
            /** Sla Reply Hours */
            sla_reply_hours?: number | null;
            /** Sla Resolve Hours */
            sla_resolve_hours?: number | null;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Checks */
            checks: components["schemas"]["CheckOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded" | "unhealthy";
            /** Version */
            version: string;
        };
        /** RelinkBody */
        RelinkBody: {
            /** New Hub Issue Id */
            new_hub_issue_id: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Ticket Id */
            ticket_id: number;
        };
        /** RelinkResponse */
        RelinkResponse: {
            /** Closed History Id */
            closed_history_id: number | null;
            /** New History Id */
            new_history_id: number;
            /** New Hub Issue Id */
            new_hub_issue_id: number;
            /** No Op */
            no_op: boolean;
            /** Old Hub Issue Id */
            old_hub_issue_id: number | null;
            /** Ticket Id */
            ticket_id: number;
        };
        /** RoutingOut */
        RoutingOut: {
            /** Auto Assigned */
            auto_assigned: number;
            /** Auto Hit Rate */
            auto_hit_rate: number;
            /** Target */
            target: string;
            /** Tickets Total */
            tickets_total: number;
        };
        /** SLAOut */
        SLAOut: {
            /** Acknowledged */
            acknowledged: number;
            /** Acknowledgement Rate */
            acknowledgement_rate: number;
            /** Escalated */
            escalated: number;
            /** Notifications Total */
            notifications_total: number;
            /** Pending */
            pending: number;
            /** Target */
            target: string;
        };
        /** ScopeRowOut */
        ScopeRowOut: {
            /** Feature */
            feature?: string | null;
            /** Id */
            id: number;
            /** Module */
            module?: string | null;
            /** Product Line Code */
            product_line_code?: string | null;
            /** User Id */
            user_id: number;
        };
        /** SourceOut */
        SourceOut: {
            /** Code */
            code: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
        };
        /** SupervisorIn */
        SupervisorIn: {
            /** Deputy Supervisor Id */
            deputy_supervisor_id?: number | null;
            /** Supervisor Id */
            supervisor_id: number;
        };
        /**
         * SyncFromFeishuIn
         * @description Either pull a whole department or a specific list of open_ids.
         */
        SyncFromFeishuIn: {
            /**
             * Department Id
             * @description Feishu department open_id; '0' = root
             */
            department_id?: string | null;
            /**
             * Open Ids
             * @description Targeted user list
             */
            open_ids?: string[] | null;
        };
        /** SyncReportOut */
        SyncReportOut: {
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
            /** New Count */
            new_count: number;
            /** New User Ids */
            new_user_ids: number[];
            /** Revived Count */
            revived_count: number;
            /** Skipped Inactive */
            skipped_inactive: number;
            /** Total Processed */
            total_processed: number;
            /** Touched User Ids */
            touched_user_ids: number[];
            /** Updated Count */
            updated_count: number;
        };
        /** TicketDetail */
        TicketDetail: {
            /** Actual Replied At */
            actual_replied_at: string | null;
            /** Actual Resolved At */
            actual_resolved_at: string | null;
            /** Assigned User Id */
            assigned_user_id: number | null;
            /** Body */
            body: string | null;
            /** Body Html */
            body_html: string | null;
            /** Cached Reply Content */
            cached_reply_content: string | null;
            /** Cached Reply Version */
            cached_reply_version: number | null;
            /** Children Ticket Ids */
            children_ticket_ids: number[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Identity Id */
            customer_identity_id: number | null;
            /** Customer Replied At */
            customer_replied_at: string | null;
            /** Expected Resolved At */
            expected_resolved_at: string | null;
            /** Feature */
            feature: string | null;
            /** Hub Issue Id */
            hub_issue_id: number | null;
            /** Id */
            id: number;
            /** Module */
            module: string | null;
            /** Parent Ticket Id */
            parent_ticket_id: number | null;
            /** Product Line Code */
            product_line_code: string | null;
            /** Received At */
            received_at: string | null;
            /** Reporter */
            reporter: {
                [key: string]: unknown;
            } | null;
            /** Short Code */
            short_code: string;
            /** Source Code */
            source_code: string | null;
            /** Source Payload */
            source_payload: {
                [key: string]: unknown;
            } | null;
            /** Source Status */
            source_status: string | null;
            /** Source Ticket Id */
            source_ticket_id: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Type */
            type: string;
        };
        /** TicketListResponse */
        TicketListResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["TicketSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** TicketSummary */
        TicketSummary: {
            /** Assigned User Id */
            assigned_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Identity Id */
            customer_identity_id: number | null;
            /** Customer Replied At */
            customer_replied_at: string | null;
            /** Feature */
            feature: string | null;
            /** Hub Issue Id */
            hub_issue_id: number | null;
            /** Id */
            id: number;
            /** Module */
            module: string | null;
            /** Product Line Code */
            product_line_code: string | null;
            /** Received At */
            received_at: string | null;
            /** Short Code */
            short_code: string;
            /** Source Code */
            source_code: string | null;
            /** Source Ticket Id */
            source_ticket_id: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** Type */
            type: string;
        };
        /**
         * UserDetailOut
         * @description Aggregated profile for /admin/users/:id frontend page.
         */
        UserDetailOut: {
            /** Feature Scopes */
            feature_scopes: components["schemas"]["ScopeRowOut"][];
            /** Module Scopes */
            module_scopes: components["schemas"]["ScopeRowOut"][];
            /** Partners */
            partners: components["schemas"]["PartnerRowOut"][];
            supervisor: components["schemas"]["app__api__admin_users__SupervisorOut"] | null;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string | null;
            /** Employee No */
            employee_no: string | null;
            /** Feishu Uid */
            feishu_uid: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Ksm Account */
            ksm_account: string | null;
            /** Linear User Id */
            linear_user_id: string | null;
            /** Mobile */
            mobile: string | null;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Zhichi Agent Id */
            zhichi_agent_id: string | null;
        };
        /** UserPatch */
        UserPatch: {
            /** Email */
            email?: string | null;
            /** Employee No */
            employee_no?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Ksm Account */
            ksm_account?: string | null;
            /** Linear User Id */
            linear_user_id?: string | null;
            /** Mobile */
            mobile?: string | null;
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Zhichi Agent Id */
            zhichi_agent_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WebhookIntakeOut */
        WebhookIntakeOut: {
            /** By Source */
            by_source: {
                [key: string]: number;
            };
            /** Deduped Total */
            deduped_total: number;
            /** Total */
            total: number;
            /** Window Hours */
            window_hours: number;
        };
        /** SupervisorOut */
        app__api__admin_users__SupervisorOut: {
            /** Deputy Supervisor Id */
            deputy_supervisor_id: number | null;
            /** Supervisor Id */
            supervisor_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Id */
            user_id: number;
        };
        /** SupervisorOut */
        app__api__metrics__SupervisorOut: {
            /** Linked Tickets */
            linked_tickets: number;
            /** Relink Count */
            relink_count: number;
            /** Relink Rate */
            relink_rate: number;
            /** Target */
            target: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_features_api_admin_features_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_feature_api_admin_features_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feature_api_admin_features__feature_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modules_api_admin_modules_get: {
        parameters: {
            query?: {
                product_line_code?: string | null;
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_module_api_admin_modules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_module_api_admin_modules__module_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_lines_api_admin_product_lines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductLineOut"][];
                };
            };
        };
    };
    patch_product_line_api_admin_product_lines__code__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductLinePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductLineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_features_api_admin_scopes_features_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                feature?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureScopeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_feature_api_admin_scopes_features_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureScopeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureScopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feature_api_admin_scopes_features__scope_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scope_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_admin_scopes_history_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                scope_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modules_api_admin_scopes_modules_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                product_line_code?: string | null;
                module?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleScopeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_module_api_admin_scopes_modules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleScopeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleScopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_module_api_admin_scopes_modules__scope_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scope_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    list_feishu_departments_api_admin_users_feishu_departments_get: {
        parameters: {
            query?: {
                parent_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeishuDeptOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feishu_department_users_api_admin_users_feishu_departments__department_id__users_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeishuContactUserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_from_feishu_api_admin_users_sync_from_feishu_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncFromFeishuIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_detail_api_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_partner_api_admin_users__user_id__partners_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartnerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_partner_api_admin_users__user_id__partners__partner_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
                partner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_supervisor_api_admin_users__user_id__supervisor_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupervisorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__admin_users__SupervisorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_supervisor_api_admin_users__user_id__supervisor_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_callback_api_auth_feishu_callback_get: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feishu_login_url_api_auth_feishu_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginUrlResponse"];
                };
            };
        };
    };
    search_customers_api_customers_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hub_issues_api_hub_issues_get: {
        parameters: {
            query?: {
                type?: string | null;
                status?: string | null;
                assigned_user_id?: number | null;
                product?: string | null;
                module?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubIssueListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hub_issue_api_hub_issues__hub_issue_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hub_issue_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubIssueDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_metrics_api_metrics_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    list_inbox_api_supervisor_inbox_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_notification_api_supervisor_notifications__notification_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relink_ticket_api_supervisor_relink_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelinkBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_tickets_get: {
        parameters: {
            query?: {
                source_code?: string | null;
                type?: string | null;
                status?: string | null;
                assigned_user_id?: number | null;
                customer_identity_id?: number | null;
                hub_issue_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_history_api_tickets__ticket_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    ksm_webhook_webhook_ksm_post: {
        parameters: {
            query: {
                access_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KSMAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zammad_webhook_webhook_zammad_post: {
        parameters: {
            query: {
                access_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zhichi_webhook_webhook_zhichi_post: {
        parameters: {
            query: {
                access_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
