"""D1 business tables: identity / 分工 / customers / tickets / hub_issues / history / KSM mapping / notification.

Revision ID: 0002_d1_business_tables
Revises: 0001_d0_initial
Create Date: 2026-05-06

Adds 14 new tables (per upgrade_plan.md §4) plus ksm_issue_type_mappings (D0 review)
plus notification_log (D6 escalation pulled forward).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_d1_business_tables"
down_revision: str | Sequence[str] | None = "0001_d0_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("primary_contact", sa.JSON(), nullable=True),
        sa.Column("merged_into_customer_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "merged_into_customer_id IS NULL OR merged_into_customer_id <> id",
            name="ck_customers_merge_self",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customers_merged_into_customer_id"),
        "customers",
        ["merged_into_customer_id"],
        unique=False,
    )
    op.create_table(
        "status_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("changed_by", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('ticket','hub_issue')", name="ck_status_history_entity"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_status_history_changed", "status_history", ["changed_at"], unique=False)
    op.create_index(
        "ix_status_history_entity",
        "status_history",
        ["entity_type", "entity_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "assignment_scope_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("action IN ('add','remove')", name="ck_scope_history_action"),
        sa.CheckConstraint("scope_type IN ('module','feature')", name="ck_scope_history_type"),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scope_history_user", "assignment_scope_history", ["user_id", "changed_at"], unique=False
    )
    op.create_table(
        "assignment_scopes_feature",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("feature", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feature", "user_id", name="uq_scope_feature"),
    )
    op.create_index(
        "ix_scope_feature_lookup", "assignment_scopes_feature", ["feature"], unique=False
    )
    op.create_table(
        "assignment_scopes_module",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_line_code", sa.String(length=64), nullable=False),
        sa.Column("module", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_line_code"],
            ["product_lines.code"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_line_code", "module", "user_id", name="uq_scope_module"),
    )
    op.create_index(
        "ix_scope_module_lookup",
        "assignment_scopes_module",
        ["product_line_code", "module"],
        unique=False,
    )
    op.create_table(
        "customer_identities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("source_code", sa.String(length=32), nullable=False),
        sa.Column("source_user_id", sa.String(length=128), nullable=True),
        sa.Column("source_custom_id", sa.String(length=128), nullable=True),
        sa.Column("erp_uid", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("mobile", sa.String(length=32), nullable=True),
        sa.Column("raw_name", sa.String(length=255), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("resolved_by_key", sa.String(length=32), nullable=False),
        sa.Column("human_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "resolved_by_key IN ('erp_uid','mobile','email','source_custom_id','manual','none')",
            name="ck_customer_identity_resolved_by_key",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_code"],
            ["sources.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_code", "source_user_id", name="uq_customer_identity_source_user"
        ),
    )
    op.create_index(
        "ix_customer_identity_customer", "customer_identities", ["customer_id"], unique=False
    )
    op.create_index("ix_customer_identity_email", "customer_identities", ["email"], unique=False)
    op.create_index(
        "ix_customer_identity_erp_uid", "customer_identities", ["erp_uid"], unique=False
    )
    op.create_index("ix_customer_identity_mobile", "customer_identities", ["mobile"], unique=False)
    op.create_index(
        "ix_customer_identity_source_custom",
        "customer_identities",
        ["source_custom_id"],
        unique=False,
    )
    op.create_table(
        "customer_merge_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_customer_id", sa.Integer(), nullable=False),
        sa.Column("to_customer_id", sa.Integer(), nullable=False),
        sa.Column("merge_reason", sa.Text(), nullable=True),
        sa.Column("merged_by", sa.String(length=64), nullable=False),
        sa.Column(
            "merged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("from_customer_id <> to_customer_id", name="ck_customer_merge_self"),
        sa.ForeignKeyConstraint(
            ["from_customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_customer_merge_from", "customer_merge_history", ["from_customer_id"], unique=False
    )
    op.create_index(
        "ix_customer_merge_to", "customer_merge_history", ["to_customer_id"], unique=False
    )
    op.create_table(
        "hub_issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("short_code", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("canonical_body", sa.Text(), nullable=True),
        sa.Column("product_line_code", sa.String(length=64), nullable=True),
        sa.Column("product", sa.String(length=128), nullable=True),
        sa.Column("module", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("reply_content", sa.Text(), nullable=True),
        sa.Column("reply_content_version", sa.Integer(), nullable=False),
        sa.Column("reply_authored_by", sa.String(length=64), nullable=True),
        sa.Column("reply_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linear_uuid", sa.String(length=64), nullable=True),
        sa.Column("linear_identifier", sa.String(length=64), nullable=True),
        sa.Column("linear_status", sa.String(length=64), nullable=True),
        sa.Column("linear_status_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_iteration", sa.String(length=64), nullable=True),
        sa.Column("expected_released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("customer_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("feishu_task_id", sa.String(length=64), nullable=True),
        sa.Column("feishu_task_status", sa.String(length=64), nullable=True),
        sa.Column("feishu_task_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expected_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_hub_issue_id", sa.Integer(), nullable=True),
        sa.Column("supersede_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "priority IS NULL OR priority IN ('critical','high','medium','low','lowest')",
            name="ck_hub_issues_priority",
        ),
        sa.CheckConstraint(
            "type IN ('Bug_fix','Demand') OR linear_uuid IS NULL",
            name="ck_hub_issues_linear_fields",
        ),
        sa.CheckConstraint(
            "type IN ('Operation','Bug_fix','Demand','Internal_task')", name="ck_hub_issues_type"
        ),
        sa.CheckConstraint(
            "type='Internal_task' OR feishu_task_id IS NULL",
            name="ck_hub_issues_internal_task_fields",
        ),
        sa.CheckConstraint(
            "type='Operation' OR (reply_content IS NULL AND reply_authored_by IS NULL)",
            name="ck_hub_issues_operation_fields",
        ),
        sa.CheckConstraint(
            "superseded_by_hub_issue_id IS NULL OR superseded_by_hub_issue_id <> id",
            name="ck_hub_issues_supersede_self",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_line_code"],
            ["product_lines.code"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_hub_issue_id"],
            ["hub_issues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_code"),
    )
    op.create_index(
        op.f("ix_hub_issues_assigned_user_id"), "hub_issues", ["assigned_user_id"], unique=False
    )
    op.create_index("ix_hub_issues_linear_uuid", "hub_issues", ["linear_uuid"], unique=False)
    op.create_index(
        "ix_hub_issues_product_module", "hub_issues", ["product", "module"], unique=False
    )
    op.create_index("ix_hub_issues_type_status", "hub_issues", ["type", "status"], unique=False)
    op.create_table(
        "ksm_issue_type_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ksm_category", sa.String(length=128), nullable=False),
        sa.Column("ksm_subcategory", sa.String(length=128), nullable=True),
        sa.Column("product_line_code", sa.String(length=64), nullable=False),
        sa.Column("target_module", sa.String(length=128), nullable=False),
        sa.Column("target_feature", sa.String(length=128), nullable=True),
        sa.Column("classification_hint", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification_hint IS NULL OR classification_hint IN ('operation','bug_fix','demand','internal_task')",
            name="ck_ksm_mapping_hint",
        ),
        sa.ForeignKeyConstraint(
            ["product_line_code"],
            ["product_lines.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ksm_category", "ksm_subcategory", name="uq_ksm_mapping_category"),
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipient_user_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("notify_type", sa.String(length=32), nullable=False),
        sa.Column("related_entity_type", sa.String(length=32), nullable=True),
        sa.Column("related_entity_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalated_to_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('feishu_bot','feishu_im','email')", name="ck_notification_channel"
        ),
        sa.CheckConstraint(
            "notify_type IN ('sla_overdue','revert_spike','assignee_assigned','escalation')",
            name="ck_notification_type",
        ),
        sa.CheckConstraint(
            "related_entity_type IS NULL OR related_entity_type IN ('ticket','hub_issue','agent_decision')",
            name="ck_notification_entity_type",
        ),
        sa.ForeignKeyConstraint(
            ["escalated_to_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_entity",
        "notification_log",
        ["related_entity_type", "related_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_recipient_pending",
        "notification_log",
        ["recipient_user_id", "sent_at"],
        unique=False,
    )
    op.create_table(
        "user_partners",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("user_id <> partner_id", name="ck_user_partners_self"),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "partner_id"),
    )
    op.create_table(
        "user_supervisors",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("supervisor_id", sa.Integer(), nullable=False),
        sa.Column("deputy_supervisor_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("user_id <> supervisor_id", name="ck_user_supervisors_self"),
        sa.ForeignKeyConstraint(
            ["deputy_supervisor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "hub_issue_relations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_hub_issue_id", sa.Integer(), nullable=False),
        sa.Column("to_hub_issue_id", sa.Integer(), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("human_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation IN ('duplicate_of','related_to','partially_overlaps')",
            name="ck_hub_issue_relations_relation",
        ),
        sa.CheckConstraint(
            "from_hub_issue_id <> to_hub_issue_id", name="ck_hub_issue_relations_self"
        ),
        sa.ForeignKeyConstraint(
            ["from_hub_issue_id"],
            ["hub_issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_hub_issue_id"],
            ["hub_issues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_hub_issue_relations_from", "hub_issue_relations", ["from_hub_issue_id"], unique=False
    )
    op.create_index(
        "ix_hub_issue_relations_to", "hub_issue_relations", ["to_hub_issue_id"], unique=False
    )
    op.create_table(
        "hub_issue_reply_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hub_issue_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("reply_content", sa.Text(), nullable=False),
        sa.Column("authored_by", sa.String(length=64), nullable=False),
        sa.Column(
            "authored_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hub_issue_id"],
            ["hub_issues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hub_issue_id", "version", name="uq_reply_history_version"),
    )
    op.create_index(
        "ix_reply_history_hub", "hub_issue_reply_history", ["hub_issue_id", "version"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("short_code", sa.String(length=32), nullable=False),
        sa.Column("source_code", sa.String(length=32), nullable=True),
        sa.Column("source_ticket_id", sa.String(length=128), nullable=True),
        sa.Column("internal_split_id", sa.String(length=64), nullable=True),
        sa.Column("source_payload", sa.JSON(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("parent_ticket_id", sa.Integer(), nullable=True),
        sa.Column("children_ticket_ids", sa.JSON(), nullable=True),
        sa.Column("customer_identity_id", sa.Integer(), nullable=True),
        sa.Column("product_line_code", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("reporter", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_status", sa.String(length=64), nullable=True),
        sa.Column("hub_issue_id", sa.Integer(), nullable=True),
        sa.Column("expected_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_iteration", sa.String(length=64), nullable=True),
        sa.Column("linear_uuid", sa.String(length=64), nullable=True),
        sa.Column("linear_identifier", sa.String(length=64), nullable=True),
        sa.Column("cached_reply_content", sa.Text(), nullable=True),
        sa.Column("cached_reply_version", sa.Integer(), nullable=True),
        sa.Column("customer_replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_user_id", sa.Integer(), nullable=True),
        sa.Column("module", sa.String(length=128), nullable=True),
        sa.Column("feature", sa.String(length=128), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("closed_reason", sa.String(length=32), nullable=True),
        sa.Column("attachments_synced", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(type IN ('Raw','Parent')  AND source_code IS NOT NULL  AND source_ticket_id IS NOT NULL  AND internal_split_id IS NULL) OR (type='Child'  AND source_code IS NULL  AND source_ticket_id IS NULL  AND internal_split_id IS NOT NULL  AND parent_ticket_id IS NOT NULL)",
            name="ck_tickets_type_fields",
        ),
        sa.CheckConstraint("type IN ('Raw','Parent','Child')", name="ck_tickets_type"),
        sa.CheckConstraint(
            "parent_ticket_id IS NULL OR parent_ticket_id <> id", name="ck_tickets_parent_self"
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_identity_id"],
            ["customer_identities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_ticket_id"],
            ["tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_line_code"],
            ["product_lines.code"],
        ),
        sa.ForeignKeyConstraint(
            ["source_code"],
            ["sources.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("internal_split_id"),
        sa.UniqueConstraint("short_code"),
    )
    op.create_index(
        op.f("ix_tickets_assigned_user_id"), "tickets", ["assigned_user_id"], unique=False
    )
    op.create_index("ix_tickets_customer", "tickets", ["customer_identity_id"], unique=False)
    op.create_index("ix_tickets_hub_issue", "tickets", ["hub_issue_id"], unique=False)
    op.create_index("ix_tickets_parent", "tickets", ["parent_ticket_id"], unique=False)
    op.create_index("ix_tickets_status", "tickets", ["status"], unique=False)
    op.create_index("ix_tickets_type", "tickets", ["type"], unique=False)
    op.create_table(
        "ticket_hub_issue_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("hub_issue_id", sa.Integer(), nullable=False),
        sa.Column(
            "effective_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("human_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hub_issue_id"],
            ["hub_issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ticket_hub_issue_history_hub",
        "ticket_hub_issue_history",
        ["hub_issue_id"],
        unique=False,
    )
    op.create_index(
        "ix_ticket_hub_issue_history_ticket",
        "ticket_hub_issue_history",
        ["ticket_id"],
        unique=False,
    )
    # users: D1 adds Linear user mapping
    op.add_column("users", sa.Column("linear_user_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_users_linear_user_id"), "users", ["linear_user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_linear_user_id"), table_name="users")
    op.drop_column("users", "linear_user_id")
    op.drop_index("ix_ticket_hub_issue_history_ticket", table_name="ticket_hub_issue_history")
    op.drop_index("ix_ticket_hub_issue_history_hub", table_name="ticket_hub_issue_history")
    op.drop_table("ticket_hub_issue_history")
    op.drop_index("ix_tickets_type", table_name="tickets")
    op.drop_index("ix_tickets_status", table_name="tickets")
    op.drop_index("ix_tickets_parent", table_name="tickets")
    op.drop_index("ix_tickets_hub_issue", table_name="tickets")
    op.drop_index("ix_tickets_customer", table_name="tickets")
    op.drop_index(op.f("ix_tickets_assigned_user_id"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index("ix_reply_history_hub", table_name="hub_issue_reply_history")
    op.drop_table("hub_issue_reply_history")
    op.drop_index("ix_hub_issue_relations_to", table_name="hub_issue_relations")
    op.drop_index("ix_hub_issue_relations_from", table_name="hub_issue_relations")
    op.drop_table("hub_issue_relations")
    op.drop_table("user_supervisors")
    op.drop_table("user_partners")
    op.drop_index("ix_notification_recipient_pending", table_name="notification_log")
    op.drop_index("ix_notification_entity", table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_table("ksm_issue_type_mappings")
    op.drop_index("ix_hub_issues_type_status", table_name="hub_issues")
    op.drop_index("ix_hub_issues_product_module", table_name="hub_issues")
    op.drop_index("ix_hub_issues_linear_uuid", table_name="hub_issues")
    op.drop_index(op.f("ix_hub_issues_assigned_user_id"), table_name="hub_issues")
    op.drop_table("hub_issues")
    op.drop_index("ix_customer_merge_to", table_name="customer_merge_history")
    op.drop_index("ix_customer_merge_from", table_name="customer_merge_history")
    op.drop_table("customer_merge_history")
    op.drop_index("ix_customer_identity_source_custom", table_name="customer_identities")
    op.drop_index("ix_customer_identity_mobile", table_name="customer_identities")
    op.drop_index("ix_customer_identity_erp_uid", table_name="customer_identities")
    op.drop_index("ix_customer_identity_email", table_name="customer_identities")
    op.drop_index("ix_customer_identity_customer", table_name="customer_identities")
    op.drop_table("customer_identities")
    op.drop_index("ix_scope_module_lookup", table_name="assignment_scopes_module")
    op.drop_table("assignment_scopes_module")
    op.drop_index("ix_scope_feature_lookup", table_name="assignment_scopes_feature")
    op.drop_table("assignment_scopes_feature")
    op.drop_index("ix_scope_history_user", table_name="assignment_scope_history")
    op.drop_table("assignment_scope_history")
    op.drop_index("ix_status_history_entity", table_name="status_history")
    op.drop_index("ix_status_history_changed", table_name="status_history")
    op.drop_table("status_history")
    op.drop_index(op.f("ix_customers_merged_into_customer_id"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
